[bastion]
bastion ansible_host=3.72.11.146 ansible_user=ec2-user ansible_ssh_private_key_file=../terraform/phpapp-key

[db]
db ansible_host=10.0.2.147 ansible_user=ec2-user ansible_ssh_private_key_file=../terraform/phpapp-key ansible_ssh_common_args='-o ProxyCommand="ssh -i ../terraform/phpapp-key ec2-user@3.72.11.146 -W %h:%p"'

[web]
web1 ansible_host=3.75.205.34 ansible_user=ec2-user ansible_ssh_private_key_file=../terraform/phpapp-key
web2 ansible_host=52.59.170.76 ansible_user=ec2-user ansible_ssh_private_key_file=../terraform/phpapp-key
web3 ansible_host=3.120.244.59 ansible_user=ec2-user ansible_ssh_private_key_file=../terraform/phpapp-key