[bastion]
bastion ansible_host=3.121.206.177

[db]
db ansible_host=10.0.2.55 ansible_ssh_common_args='-o ProxyCommand="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ../terraform/phpapp-key ec2-user@3.121.206.177 -W %h:%p"'

[web]
web1 ansible_host=18.192.122.214
web2 ansible_host=18.196.64.184
web3 ansible_host=3.70.129.247
